version: '3.8' 
services:
  frontend:
    image: git.inet.co.th:5555/erp/mini_erp_frontend/uat:latest
    ports:
      - "5800:80"
    networks:
      - frontend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: any
      resources:
        limits:
          #cpus: "1.0"
          memory: 100M

networks:
    frontend:
        external: true
