version: "3.8"
services:
  frontend:
    image: git.inet.co.th:5555/erp/mini_erp_frontend/prd:latest
    ports:
      - "5800:80"
    deploy:
      mode: replicated
      replicas: 9
      placement:
        max_replicas_per_node: 3
      restart_policy:
        condition: any
      resources:
        limits:
          #cpus: "1.0"
          memory: 100M
    networks:
      - front

networks:
  front:
    external: true
